# config
rss:            # link
favicon: https://i.loli.net/2017/11/26/5a19c0b50432e.png
blog_logo: 
header_image: https://i.loli.net/2017/11/26/5a19c56faa29f.jpg
post_toc: true

# menu
menu:
  About: /about
  Archives: /archives
  # you can add here

# author
author_image:   # link

# Social Links
social:
  weibo: 
  github: https://github.com/xzhih
  twitter: 
  facebook: 
  # You only can use that I have added, I will keep adding

# Footer Links
footer: 
  # title: link
  # 粤ICP备xxxxxxx号-x: http://www.miitbeian.gov.cn
  # 粤公网安备xxxxxxx号: http://www.beian.gov.cn

# widget
widgets:
  recent_posts: true
  category: true
  tagcloud: true
  # This is a simple theme, I think 3 is enough.

# gallery
# https://github.com/sachinchoolur/lightgallery.js
lightgallery: true

# https://valine.js.org
comment: false
valine:
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki 
  verify: false # Verification code
  appId: # your leancloud application appid
  appKey: # your leancloud application appkey
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  pageSize: 10 # pagination size