# config
rss:            # link
favicon: https://i.loli.net/2017/11/26/5a19c0b50432e.png
blog_logo: 
header_image: https://i.loli.net/2017/11/26/5a19c56faa29f.jpg
sec_title: This is a demo
post_toc: true

# keywords
keywords: hexo, casper, ghost, theme

# menu
menu:
  About: /about
  Archives: /archives
  # you can add here

# author
author_image:   # link

# Social Links
social:
  weibo: https://weibo.com/xzhih
  github: https://github.com/xzhih
  twitter: https://twitter.com
  facebook: https://facebook
  telegram:
  # You only can use that I have added, I will keep adding

# Footer Links
footer_text: 
  # title: link
  # 粤ICP备xxxxxxx号-x: http://www.miitbeian.gov.cn
  # 粤公网安备xxxxxxx号: http://www.beian.gov.cn

# widget
widgets:
  recent_posts: true
  category: true
  tagcloud: true
  # This is a simple theme, I think 3 is enough.

# gallery
# https://github.com/sachinchoolur/lightgallery.js
lightgallery: true

# comment
# https://valine.js.org
comment: false
valine:
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki 
  verify: false # Verification code
  appId: # your leancloud application appid
  appKey: # your leancloud application appkey
  placeholder: Just go go # comment box placeholder
  pageSize: 10 # pagination size
  avatar: mm # gravatar style

chromeNavColor: 3c484e

# Baidu Push
baidu: false

# Google Analytics
googleAnalytics: false
GA_TRACKING_ID: UA-XXXXXXXXXX-1

# Your Own CDN Links
# if you don't need the default cdn links, just delete, this theme will get files from source  
CDN: 
  jquery: https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js
  highlightjs: https://cdn.staticfile.org/highlight.js/9.10.0/highlight.min.js
  lightgalleryjs: https://cdn.staticfile.org/lightgallery/1.3.9/js/lightgallery.min.js
  lightgallerycss: https://cdn.staticfile.org/lightgallery/1.3.9/css/lightgallery.min.css